name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }} # assign pull request author
          reviewers: haeni82,pwc2002,seojin15,hdg0116 # if draft, assigned when draft is released
